name: weather_app_test
description: A new Flutter project.


environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  http: ^0.13.4
  rounded_loading_button: ^2.1.0
  flutter_lints: ^1.0.0
  firebase_auth: ^3.3.11
  tuple: ^2.0.0
  font_awesome_flutter: ^10.1.0
  dio: ^4.0.6
  path_provider: ^2.0.9

  #Location
  location: ^4.3.0
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.3

  hive: ^2.0.6
  hive_flutter: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  json_serializable:
  hive_generator: ^1.1.2
  mocktail: ^0.3.0





flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - assets/